# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'MEAP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MEAP

  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Charts'

  target 'MEAPTests' do
    # inherit! :search_paths
    # Pods for testing
  end

  target 'MEAPUITests' do
    # inherit! :search_paths
    # Pods for testing
  end
  
end


